<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
	  <ProjectReference
	  Include="..\FinancasPessoais.Domain\FinancasPessoais.Domain.csproj" />
	  <ProjectReference Include="..\FinancasPessoais.Application\FinancasPessoais.Application.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.11" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
		<PackageReference Include="SourceGear.sqlite3" Version="3.50.4.5" />
	</ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
