// <auto-generated />
using System;
using FinancasPessoais.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancasPessoais.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726191957_InitialCreate_V1")]
    partial class InitialCreate_V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Anexo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoInterno")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MovimentacaoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PagamentoId")
                        .HasColumnType("TEXT");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoMime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovimentacaoId");

                    b.HasIndex("PagamentoId");

                    b.ToTable("Anexos");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoriaPaiId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cor")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Icone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoPadrao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPaiId");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Cor = "#FF5733",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icone = "🍔",
                            Nome = "Alimentação",
                            Origem = "Manual",
                            TipoPadrao = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Cor = "#33FF57",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icone = "🚗",
                            Nome = "Transporte",
                            Origem = "Manual",
                            TipoPadrao = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Cor = "#3357FF",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icone = "💰",
                            Nome = "Salário",
                            Origem = "Manual",
                            TipoPadrao = 0
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Cor = "#FF33F6",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icone = "🏠",
                            Nome = "Moradia",
                            Origem = "Manual",
                            TipoPadrao = 1
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Cor = "#FF3333",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icone = "🏥",
                            Nome = "Saúde",
                            Origem = "Manual",
                            TipoPadrao = 1
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Cor = "#33FFF6",
                            CriadoEm = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Icone = "🎮",
                            Nome = "Lazer",
                            Origem = "Manual",
                            TipoPadrao = 1
                        });
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.ContaFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Arquivado")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instituicao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SaldoInicial")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ContasFinanceiras");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Movimentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Competencia")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PessoaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Situacao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("TransferenciaRelacionadaId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Vencimento")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ContaId");

                    b.HasIndex("PessoaId");

                    b.HasIndex("TransferenciaRelacionadaId")
                        .IsUnique();

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Desconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Juros")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovimentacaoId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Multa")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContaId");

                    b.HasIndex("MovimentacaoId");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Transferencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaDestinoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContaOrigemId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExcluidoEm")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MovimentacaoEntradaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("MovimentacaoSaidaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Tarifa")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContaDestinoId");

                    b.HasIndex("ContaOrigemId");

                    b.HasIndex("MovimentacaoEntradaId")
                        .IsUnique();

                    b.HasIndex("MovimentacaoSaidaId")
                        .IsUnique();

                    b.ToTable("Transferencias");
                });

            modelBuilder.Entity("MovimentacaoTag", b =>
                {
                    b.Property<Guid>("MovimentacoesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagsId")
                        .HasColumnType("TEXT");

                    b.HasKey("MovimentacoesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("MovimentacaoTag");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Anexo", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Movimentacao", "Movimentacao")
                        .WithMany("Anexos")
                        .HasForeignKey("MovimentacaoId");

                    b.HasOne("FinancasPessoais.Domain.Entities.Pagamento", "Pagamento")
                        .WithMany("Anexos")
                        .HasForeignKey("PagamentoId");

                    b.Navigation("Movimentacao");

                    b.Navigation("Pagamento");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Categoria", "CategoriaPai")
                        .WithMany("Subcategorias")
                        .HasForeignKey("CategoriaPaiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaPai");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Movimentacao", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.ContaFinanceira", "Conta")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.Pessoa", "Pessoa")
                        .WithMany("Movimentacoes")
                        .HasForeignKey("PessoaId");

                    b.HasOne("FinancasPessoais.Domain.Entities.Movimentacao", "TransferenciaRelacionada")
                        .WithOne()
                        .HasForeignKey("FinancasPessoais.Domain.Entities.Movimentacao", "TransferenciaRelacionadaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("Pessoa");

                    b.Navigation("TransferenciaRelacionada");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.ContaFinanceira", "Conta")
                        .WithMany()
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.Movimentacao", "Movimentacao")
                        .WithMany("Pagamentos")
                        .HasForeignKey("MovimentacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");

                    b.Navigation("Movimentacao");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Transferencia", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.ContaFinanceira", "ContaDestino")
                        .WithMany()
                        .HasForeignKey("ContaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.ContaFinanceira", "ContaOrigem")
                        .WithMany()
                        .HasForeignKey("ContaOrigemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.Movimentacao", "MovimentacaoEntrada")
                        .WithOne()
                        .HasForeignKey("FinancasPessoais.Domain.Entities.Transferencia", "MovimentacaoEntradaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinancasPessoais.Domain.Entities.Movimentacao", "MovimentacaoSaida")
                        .WithOne()
                        .HasForeignKey("FinancasPessoais.Domain.Entities.Transferencia", "MovimentacaoSaidaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContaDestino");

                    b.Navigation("ContaOrigem");

                    b.Navigation("MovimentacaoEntrada");

                    b.Navigation("MovimentacaoSaida");
                });

            modelBuilder.Entity("MovimentacaoTag", b =>
                {
                    b.HasOne("FinancasPessoais.Domain.Entities.Movimentacao", null)
                        .WithMany()
                        .HasForeignKey("MovimentacoesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancasPessoais.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Movimentacoes");

                    b.Navigation("Subcategorias");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.ContaFinanceira", b =>
                {
                    b.Navigation("Movimentacoes");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Movimentacao", b =>
                {
                    b.Navigation("Anexos");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Pagamento", b =>
                {
                    b.Navigation("Anexos");
                });

            modelBuilder.Entity("FinancasPessoais.Domain.Entities.Pessoa", b =>
                {
                    b.Navigation("Movimentacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
