<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android;net10.0-ios;net10.0-maccatalyst;net10.0-windows10.0.19041.0</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\FinancasPessoais.Application\FinancasPessoais.Application.csproj" />
		<ProjectReference Include="..\FinancasPessoais.Infrastructure\FinancasPessoais.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.20" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0" />

		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.android" Version="2.1.12" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.ios" Version="2.1.12" />
		<PackageReference Include="SourceGear.sqlite3" Version="3.50.4.5" />
	</ItemGroup>

</Project>